### ISSUE TITLE
Doesn't seems to work on Firefox

### ISSUE THREAD

**Issue by guillaumebaeriswyl** [sabjorn/BandcampEnhancementSuite#168]
Hello,
Unfortunately, it seems that the app doesn't work on Firefox. I don't see any new features on bandcamp... Am I the only one? 
Such a shame because using it on chrome work like a charm…
Thanks !

**Comment by sabjorn** [comment]
There are 85 users on Firefox and thus far I haven't gotten any complaints. There are some issue between how Chrome and Firefox handle extensions (especially since Google made the Manifest V3 standard) and I haven't been able to extensively test the Firefox version.

From some digging it looks like this is a permissions issue. According to [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions) page -- since June 2023 Firefox will no longer automatically have a popup to ask for permissions to be granted. So, if it is a permissions issue -- the page also shows me what to modify in my code to get a popup to happen.

However, this could be some issue so I'll need some help.

To validate this issue for me, try this:

In the browser try navigating to: 

```
about:addons
```

next to Bandcamp Enhancement Suite click *...* -> *Manage*.

navigate to the *Permissions* tab. enable all the permissions and restart the browser.

**Comment by sabjorn** [comment]
@guillaumebaeriswyl I figured out what was wrong in the code. I am pushing a release later today.

The permissions thing might still be an issue -- which I will update on the Firefox page

**Comment by guillaumebaeriswyl** [comment]
thank you! permission was the issue.

**Comment by sabjorn** [comment]
@guillaumebaeriswyl excellent. can you please update the text on your review?
