### ISSUE TITLE
1-click buy causes cart to clear

### ISSUE THREAD

**Issue by sabjorn** [sabjorn/BandcampEnhancementSuite#202]
1-click buy can cause the users cart to completely clear.

for now, the feature has been disabled in: https://github.com/sabjorn/BandcampEnhancementSuite/commit/3424ffe47edf5faa2ebf1cb8d0e319952601e572

**Comment by sabjorn** [comment]
seems like it is related to adding $0 items to the cart -- which Bandcamp doesn't actually allow

**Comment by sabjorn** [comment]
hopefully fixed with: [3e7c538](https://github.com/sabjorn/BandcampEnhancementSuite/commit/3e7c5388187b16a64aca56378edb9923bada7415)

**Comment by mr-salty** [comment]
I'm seeing this issue and confirmed I have 1.10.4 (ChromeOS Version 130.0.6723.126 (Official Build) (64-bit))

adding this track (which is not NYP/$0) using the 1-click box (either with the default $1 price or after changing it to $2) seems to reliably clear my cart: https://cheekface.bandcamp.com/track/hard-mode

Too bad bc canned me or I could look at some backend logs and figure out what's happening. fixing cart and checkout bugs was my personal mission while I was there - I fixed a lot of them there were still plenty left that I'm guessing no one is working on. 😦

**Comment by sabjorn** [comment]
@mr-salty daaaang it. This is so frustrating. But also this track also breaks for me so at least I have a reliable way to re-create! Let me know if you have any thoughts our ideas on what might be causing the issue.

**Comment by mr-salty** [comment]
thanks!  IIRC there are far too many code paths where it throws up its arms and nukes the cart. I mean, in this case, removing the "bad" item from the cart instead of tossing all the items seems like an obvious solution, alas...

"The contents of your cart have changed" is my other nemesis, and that sometimes leads to a cart clear, or sometimes happens persistently due to some or other bug.  A couple bcfridays ago I lost a *huge* cart right before the end of bcfriday and cursed myself for not screenshotting or copy/pasting before I hit "checkout".  So, I'm very happy to see the "export" function you added - so at least if it happens again I'll be able to rebuild it.
