### ISSUE TITLE
repeat button

### ISSUE THREAD

**Issue by elfh78** [sabjorn/BandcampEnhancementSuite#64]
your addon is superb. maybe it is possible to add repeat button for an album?

**Comment by sabjorn** [comment]
@elfh78 thanks for the feedback. I am really stoked to know this thing is positively impacting peoples lives.

>  maybe it is possible to add repeat button for an album?

can you elaborate a little bit on what you have in mind? I am assuming you mean: a toggle that when enabled would allow an album to restart after all tracks have finished.

If this is correct, I foresee a couple of issue:
1) On Bandcamp, after a number of plays of a track, a popup comes up essentially asking you to buy. So, infinite repeat is likely not easy to implement because of this popup.
2) This is a bit against the grain of the purpose of the extension. In general, I love Bandcamp because it allows for direct support of artists. So, I see this feature transforming it into a "Spotify" like service (but with zero royalties). I would prefer people buy albums and enable repeat on their media player.

But, this response isn't meant to be critical. I don't think it is a bad idea but maybe not a good fit for this extension. However, perhaps I have misunderstood your request. If so, please provide more detail.

**Comment by elfh78** [comment]
you understood correctly. for some reason. your extension allows me to play albums even after that pop up with paywall, if i switch to preview mode. i used to clean cookies for that before. alas, i can't support artists, because of poverty and personal problems, but i see your point. i enjoy using spotify, but i also don't like current situation with artist's earnings. i make music myself, but never profited from it and don't really know ways to do that. i listen mainly artists whos music is barely sellable, but they put price on it, anyway. in most cases no one buys it. i never even tried to put price on my music, because i see monetary profits impossible in my case. i'd also like some kind of continuous play of all albums on any account, but i see now, this is not your concept.

**Comment by sabjorn** [comment]
@elfh78 it is very interesting that the paywall popup does not prevent the playing of tracks. Definitely not intentional but I'm not going to do anything to stop it so consider it a secret "feature".

don't hesitate to post more feature requests here. I'm always trying to improve this thing.
