### ISSUE TITLE
Encapsulate cURL URLs in quotation marks

### ISSUE THREAD

**Issue by lord-carlos** [sabjorn/BandcampEnhancementSuite#88]
Hi

I have some trouble running the generated cURL in my terminal. Both copy paste or even change the first line into `#!/usr/bin/env bash` and run it with` ./bancamp.txt`
It does however work like charm if I put the URL in quotation marks. As far as I am aware that should not have any negative effect and make it broadly usable for different terminals and shells.

Proposed changes:
* Encapsulate URLs in quotation marks
* Add `#!/usr/bin/env bash` to make it easier to execute as script. People can still copy&paste the curl command if they prefer it.

Can someone on a mac test `curl -OJ "some.file.url"`?

**Comment by sabjorn** [comment]
Hi!

Okay, so let me just say this first: thank you for the feedback. It means a lot to me knowing this tool is useful for other people.

So, I can definitely update based on your suggestion. It is super easy. BUT, I am planning on changing this feature so that the downloads will automatically be zipped and then you can directly download that through the browser. This is likely the next major feature I will be working on (I think it has the most value out of anything I have planned). BUT, it probably won't be available until sometime later summer (it really depends on how many rainy days happen here).

In any case, I honestly had no idea anyone but me would actually use this `cURL` feature. So, I think this means I should really just fix it. I will try to get a release out sometime this weekend.

Also, if you have any other feedback, comments, or suggestions: feel free to add an issue to the project. I want to make this thing better, even if I am really really slow at it...

**Comment by sabjorn** [comment]
released in https://github.com/sabjorn/BandcampEnhancementSuite/releases/tag/v1.3.1

**Comment by sabjorn** [comment]
@lord-carlos submitted the update to Google. It usually takes a day for it to be published. 

Keep an eye out for `v1.3.1`

also, again, thanks for the feedback!

**Comment by lord-carlos** [comment]
Well that was quick :0 Thank you.

I would have been fine with waiting for next release and browser based zip as well :)

**Comment by sabjorn** [comment]
@lord-carlos no worries. it was really easy and honestly it's a good practice to be able to release with minimal effort.

looks like `v1.3.1` has been published

**Comment by sabjorn** [comment]
@lord-carlos would you be interested in talking over email? I'd like to get some info from you about how you use this tool. No pressure though.

**Comment by lord-carlos** [comment]
Sure, I send a quick mail to the one from your profile. Then you have mine.
